changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Security
      labels:
        - security
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - ci
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot[bot]
