# Analysis options for Prosepal
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_build_context_synchronously: ignore
  plugins:
    - custom_lint

linter:
  rules:
    # Code quality
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - prefer_final_in_for_each
    - sort_constructors_first
    - unawaited_futures
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - use_colored_box
    - use_decorated_box
    # Safety
    - cancel_subscriptions
    - close_sinks
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - throw_in_finally
    - unnecessary_statements
    # Style
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_escaping_inner_quotes
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_returning_this
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - join_return_with_assignment
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - noop_primitive_operations
    - omit_local_variable_types
    - prefer_asserts_in_initializer_lists
    - prefer_constructors_over_static_methods
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - prefer_null_aware_method_calls
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_raw_strings
    - use_string_buffers

# Riverpod Lint - strict mode
custom_lint:
  rules:
    # Errors - must fix
    - riverpod_final_provider: error
    - notifier_extends: error
    - async_notifier_extends: error
    - missing_provider_scope: error
    - provider_dependencies: error
    - scoped_providers_should_specify_dependencies: error
    - avoid_ref_inside_state_dispose: error
    
    # Warnings - should fix  
    - functional_ref: warning
    - avoid_build_context_in_providers: warning
    - avoid_public_notifier_properties: warning
    - protected_notifier_properties: warning
    - unsupported_provider_value: warning
    - stateless_ref: warning
    - avoid_notifier_constructors: warning
    
    # Info - best practices
    - avoid_manual_providers_as_generated_provider_dependency: info
    - provider_parameters: info
