name: Bug report
description: Report a defect with clear reproduction details.
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please provide enough detail to reproduce reliably.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: A concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact sequence and data used.
      placeholder: |
        1. Go to ...
        2. Tap ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Device, OS version, app version/commit, and build type.
      placeholder: iPhone 14 Pro, iOS 26.3, commit abc123, debug/release
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and screenshots
      description: Paste relevant logs or attach screenshots.
    validations:
      required: false

