import 'package:flutter/material.dart';
import 'package:gap/gap.dart';

import '../../shared/theme/app_colors.dart';
import '../../shared/theme/app_spacing.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Terms of Service')),
      body: ListView(
        padding: EdgeInsets.all(AppSpacing.screenPadding),
        children: [
          _LegalSection(
            title: 'Using Prosepal',
            content:
                'Prosepal helps you write greeting card messages using AI. You\'re responsible for how you use the generated content.',
          ),
          _LegalSection(
            title: 'Subscriptions',
            content:
                '• Free: 3 message generations\n• Pro: 500 messages/month (resets each billing cycle)\n• Payments processed via App Store',
          ),
          _LegalSection(
            title: 'Don\'t Use For',
            content:
                '• Harmful, illegal, or offensive content\n• Harassment or hate speech\n• Spam or automated abuse',
          ),
          _LegalSection(
            title: 'Our Limits',
            content:
                'The service is provided "as is". We can\'t guarantee AI outputs will always meet your expectations.',
          ),
          _LegalSection(title: 'Contact', content: 'support@prosepal.app'),
          Gap(AppSpacing.lg),
          Text(
            'Last updated: December 2024',
            style: Theme.of(
              context,
            ).textTheme.bodySmall?.copyWith(color: AppColors.textHint),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }
}

class PrivacyScreen extends StatelessWidget {
  const PrivacyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Privacy Policy')),
      body: ListView(
        padding: EdgeInsets.all(AppSpacing.screenPadding),
        children: [
          _LegalSection(
            title: 'What We Collect',
            content:
                '• Email and display name\n• Message inputs (occasion, relationship, tone)\n• Basic device info for bug fixes',
          ),
          _LegalSection(
            title: 'AI-Generated Content',
            content:
                'Messages are generated by Google Gemini AI based on your inputs. Content is not stored or used for AI training. AI outputs may vary and should be reviewed before use.',
          ),
          _LegalSection(
            title: 'What We Don\'t Do',
            content:
                '• Sell your data\n• Store generated messages\n• Share data for ads',
          ),
          _LegalSection(
            title: 'Your Rights',
            content:
                'You can delete your account anytime from Settings. All your data will be removed within 30 days.',
          ),
          _LegalSection(title: 'Contact', content: 'support@prosepal.app'),
          Gap(AppSpacing.lg),
          Text(
            'Last updated: December 2024',
            style: Theme.of(
              context,
            ).textTheme.bodySmall?.copyWith(color: AppColors.textHint),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }
}

class _LegalSection extends StatelessWidget {
  const _LegalSection({required this.title, required this.content});

  final String title;
  final String content;

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.only(bottom: AppSpacing.md),
      padding: EdgeInsets.all(AppSpacing.md),
      decoration: BoxDecoration(
        color: AppColors.surfaceVariant,
        borderRadius: BorderRadius.circular(AppSpacing.radiusMedium),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: Theme.of(
              context,
            ).textTheme.titleSmall?.copyWith(fontWeight: FontWeight.w600),
          ),
          Gap(AppSpacing.sm),
          Text(
            content,
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
              color: AppColors.textSecondary,
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }
}
